version: '3'

services:
   blocktrivia:
     build: ./
     restart: unless-stopped
     environment:
       VIRTUAL_HOST: ${DOMAINS}
       LETSENCRYPT_HOST: ${DOMAINS}
       LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
       PORT: ${PORT}

networks:
    default:
       external:
         name: ${NETWORK}